---
name: Unit tests
on: push

jobs:
  dzil:
    runs-on: ubuntu-latest
    name: run unit tests with dzil
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Installing dependencies and testing all using dzil
        uses: jonasbn/github-action-perl-dist-zilla@0.3.0
        with:
          dzil-arguments: 'test --all'

